# Generated by Django 5.2.1 on 2026-08-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='runpod_delay_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='runpod_execution_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
