# Generated by Django 5.2.1 on 2026-08-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igen', '0002_job_runpod_delay_time_ms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=64, unique=True)),
                ('label', models.CharField(help_text='Who this was issued to.', max_length=100)),
                ('scope', models.CharField(choices=[('app', 'App'), ('metrics', 'Metrics')], max_length=10)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
