# Generated by Django 5.2.1 on 2026-08-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igen', '0003_accesskey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='dispatch_mode',
        ),
        migrations.AddField(
            model_name='accesskey',
            name='cooldown_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
